on:
  push:
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  check_conflicts:
    name: Check for PR merge conflicts
    runs-on: ubuntu-latest
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "conflict"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
